export const DEFAULT_RECRUITER_LIST = [
  { id: '1', name: 'Adirala sathvika', email: 'No email' },
  { id: '2', name: 'Arvind GR', email: 'arvind.gr@metaforgeit.com' },
  { id: '3', name: 'Charlie Darwin', email: 'charlie@metaforgeit.com' },
  { id: '4', name: 'Harini Sindey', email: 'harini.s@metaforgeit.com' },
  { id: '5', name: 'Harish Gadipally', email: 'harish.g@metaforgeit.com' },
  { id: '6', name: 'Puttapaka Saiteja', email: 'saiteja.p@metaforgeit.com' },
  { id: '7', name: 'Kallol Chakraborty', email: 'kallol.c@ltts.com' },
  { id: '8', name: 'Marcus Chen', email: 'm.chen@talentflow.io' },
  { id: '9', name: 'Sarah Kim', email: 's.kim@talentflow.io' },
  { id: '10', name: 'David Park', email: 'd.park@talentflow.io' },
  { id: '11', name: 'Alex Turner', email: 'alex.t@dev.com' },
  { id: '12', name: 'Nina Brooks', email: 'n.brooks@talentflow.io' },
  { id: '13', name: 'Priya Sharma', email: 'priya.s@talentflow.io' },
  { id: '14', name: 'James O\'Brien', email: 'j.obrien@talentflow.io' },
  { id: '15', name: 'Carlos Rivera', email: 'c.rivera@talentflow.io' },
  { id: '16', name: 'Tejasree Chakravarthy', email: 'tejasree@metaforgeit.com' },
  { id: '17', name: 'Rahul Verma', email: 'rahul.v@metaforgeit.com' },
]
