export interface ClientTrackerPreset {
  headerColor: string
  columns: string[]
  subtitle: string
}

export const CLIENT_TRACKER_PRESETS: Record<string, ClientTrackerPreset> = {
  'METAFORGE (INTERNAL)': {
    headerColor: '#C5E0B4', // Light Sage Green
    subtitle: 'Metaforge Internal Layout: Light Sage Green header (#C5E0B4) with 18 candidate tracking fields.',
    columns: [
      'Sl No',
      'Submission Date',
      'Skillset',
      'Candidate Name',
      'Contact Number',
      'Email id',
      'Total Yrs of Exp',
      'Relevant Exp',
      'Current Company',
      'Current CTC',
      'Expected CTC/Rate card',
      'Notice period',
      'Current Location',
      'Preferred Location',
      'Availability for Interview',
      'Reason',
      'Offer in Hand',
      'Linkedin URL',
    ],
  },
  'LTTS / L&T': {
    headerColor: '#FFB800', // Bright Golden Amber / Orange Yellow
    subtitle: 'LTTS / L&T Layout: Bright Golden Amber header (#FFB800) with 17 candidate tracking fields.',
    columns: [
      'Sl.No',
      'Vendor Name',
      'BU/IS',
      'Position/ Title',
      'Skill',
      'Resumes sent Date (DDMMYY)',
      'Full Name of the candidate',
      'Last Full Time Qualification',
      'MOBILE NO',
      'Mail ID',
      'NP(Days)',
      'Total Exp',
      'Relevant Exp',
      'Current Location',
      'Job Location',
      'Current Organization',
      'Rate per Month',
    ],
  },
  'Continental Automotive': {
    headerColor: '#FCE4D6', // Soft Peach
    subtitle: 'Continental Automotive Layout: Light peach header row (#FCE4D6) with technical assessment fields.',
    columns: [
      'Sl No',
      'Candidate Name',
      'Skillset',
      'Total Yrs of Exp',
      'Relevant Exp',
      'Current Location',
      'Current CTC',
      'Expected CTC/Rate card',
      'Notice period',
      'Contact Number',
      'Email id',
    ],
  },
  'Bosch Global': {
    headerColor: '#D9E1F2', // Soft Blue
    subtitle: 'Bosch Global Layout: Soft blue header row (#D9E1F2) with Bosch sourcing tracker format.',
    columns: [
      'Sl No',
      'Candidate Name',
      'Skillset',
      'Total Yrs of Exp',
      'Current Company',
      'Current Location',
      'Notice period',
      'Expected CTC/Rate card',
      'Contact Number',
      'Email id',
    ],
  },
  'Accenture Enterprise': {
    headerColor: '#7C5CFC', // Medium Purple / Violet
    subtitle: 'Accenture Layout: Medium Purple header (#7C5CFC) with 35 vendor Beeline tracking fields & Govt ID verification.',
    columns: [
      'Sl. NO',
      'RV ID',
      'Date of Submission',
      'Candidate DOB',
      'Req ID',
      'Beeline ID',
      'First Name',
      'Last Name',
      'Contact Number',
      'Email ID',
      'Gender',
      'Primary Skill',
      'Total Experience',
      'Relevant Experience',
      'Current Location',
      'Job Location',
      'Notice Period in days',
      'Acc Ex Emp/Cont',
      'Ex Employee- EMP ID',
      'Current CTC (Monthly)',
      'Exp CTC (Monthly)',
      'Mark up %',
      'Final Bill Rate Monthly (Exp CTC + mark up)',
      'Supplier name',
      'Current Employer Name',
      'Available Documents',
      'Previous Employer Name',
      'Available Documents (Prev)',
      'Highest Education',
      'Name of college for highest education',
      'Name of University for highest education',
      'Technical Evaluation',
      'Technical Assessment proof attached in Resume',
      'PAN Card Number',
      'OT Amount',
    ],
  },
  'ITC Infotech': {
    headerColor: '#FFFF00', // Pure Vibrant Yellow
    subtitle: 'ITC Infotech Layout: Pure Yellow header (#FFFF00) with 18 candidate tracking & SO fields.',
    columns: [
      'S.No',
      'Skill',
      'Candidate Name',
      'Total experience',
      'Relevant experience',
      'Candidate Mobile Number',
      'Email ID',
      'Current Payroll Company',
      'CTC',
      'ECTC',
      'Official Notice Period /Serving NP (LWD Date)',
      'Current Location',
      'Work Location',
      'Highest Education',
      'Interview date',
      'Interview time',
      'SO Number',
      'Status',
    ],
  },
}
