import { Role, ActivityLogItem } from '../../../types'

export interface RecruiterLoginRecord {
  id: string
  userName: string
  userEmail: string
  userRole: Role
  userAvatar: string
  firstEverLoginTimestamp: string
  logDate: string
  loginTime: string
  logoutTime: string
  sessionDuration: string
  activeScreenTime: string
  ipAddress: string
  deviceInfo: string
  status: 'Active Now' | 'Logged Out' | 'Timed Out'
  actionsLoggedCount: number
}

export const INITIAL_LOGIN_RECORDS: RecruiterLoginRecord[] = [
  {
    id: 'LGN-9001',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    firstEverLoginTimestamp: 'Jan 12, 2026 at 08:30:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:15:22 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 32m',
    activeScreenTime: '2h 52m',
    ipAddress: '192.168.1.45',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Active Now',
    actionsLoggedCount: 14,
  },
  {
    id: 'LGN-9002',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    firstEverLoginTimestamp: 'Jan 12, 2026 at 08:30:00 AM',
    logDate: 'Sep 08, 2026',
    loginTime: '09:02:14 AM',
    logoutTime: '06:45:10 PM',
    sessionDuration: '9h 42m',
    activeScreenTime: '7h 12m',
    ipAddress: '192.168.1.45',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Logged Out',
    actionsLoggedCount: 28,
  },
  {
    id: 'LGN-9003',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    firstEverLoginTimestamp: 'Jan 12, 2026 at 08:30:00 AM',
    logDate: 'Sep 07, 2026',
    loginTime: '09:10:05 AM',
    logoutTime: '06:30:00 PM',
    sessionDuration: '9h 19m',
    activeScreenTime: '6h 50m',
    ipAddress: '192.168.1.45',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Logged Out',
    actionsLoggedCount: 22,
  },
  {
    id: 'LGN-9004',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'P',
    firstEverLoginTimestamp: 'Feb 01, 2026 at 09:00:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:30:15 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 17m',
    activeScreenTime: '2h 15m',
    ipAddress: '192.168.1.52',
    deviceInfo: 'macOS Sonoma / Safari 17',
    status: 'Active Now',
    actionsLoggedCount: 9,
  },
  {
    id: 'LGN-9005',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'P',
    firstEverLoginTimestamp: 'Feb 01, 2026 at 09:00:00 AM',
    logDate: 'Sep 08, 2026',
    loginTime: '09:15:00 AM',
    logoutTime: '06:15:30 PM',
    sessionDuration: '9h 00m',
    activeScreenTime: '6h 40m',
    ipAddress: '192.168.1.52',
    deviceInfo: 'macOS Sonoma / Safari 17',
    status: 'Logged Out',
    actionsLoggedCount: 19,
  },
  {
    id: 'LGN-9006',
    userName: 'Suresh Kulkarni',
    userEmail: 'suresh.k@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'S',
    firstEverLoginTimestamp: 'Mar 15, 2026 at 09:15:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:45:00 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 02m',
    activeScreenTime: '2h 05m',
    ipAddress: '192.168.1.60',
    deviceInfo: 'Windows 11 / Edge 126',
    status: 'Active Now',
    actionsLoggedCount: 11,
  },
]

export const MOCK_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: 'LOG-1001',
    user: 'Marcus Chen',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    role: 'recruiter',
    userAvatar: 'M',
    action: 'Candidate Submission',
    details: 'Submitted Priyanka Sharma for REQ-2026-08-12-001 (TPC - C# Automation)',
    timestamp: 'Today at 01:45 PM',
    ipAddress: '192.168.1.45',
    category: 'Candidate Submission',
    targetEntity: 'Candidate',
    status: 'Success',
  },
  {
    id: 'LOG-1002',
    user: 'Harish Gadipally',
    userName: 'Harish Gadipally',
    userEmail: 'harish.g@metaforgeit.com',
    userRole: 'superadmin',
    role: 'superadmin',
    userAvatar: 'H',
    action: 'Requirement Created',
    details: 'Created new Job Demand: Senior AUTOSAR Architect for LTTS',
    timestamp: 'Today at 11:30 AM',
    ipAddress: '192.168.1.10',
    category: 'Requirement Management',
    targetEntity: 'Requirement',
    status: 'Success',
  },
  {
    id: 'LOG-1003',
    user: 'Priya Sharma',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    role: 'recruiter',
    userAvatar: 'P',
    action: 'Candidate Added',
    details: 'Uploaded resume for Candidate: Rajesh V (Java Backend Specialist)',
    timestamp: 'Today at 10:15 AM',
    ipAddress: '192.168.1.52',
    category: 'Candidate Upload',
    targetEntity: 'Candidate',
    status: 'Success',
  },
  {
    id: 'LOG-1004',
    user: 'Sarah Kim',
    userName: 'Sarah Kim',
    userEmail: 's.kim@talentflow.io',
    userRole: 'lead',
    role: 'lead',
    userAvatar: 'S',
    action: 'Forward Approved',
    details: 'Approved Forward Request for Priyanka Sharma on LTTS account',
    timestamp: 'Yesterday at 05:20 PM',
    ipAddress: '192.168.1.33',
    category: 'Forward Loop Approval',
    targetEntity: 'Submission',
    status: 'Success',
  },
]
