export interface ScreenshotSubmission {
  id: string
  candidateName: string
  requirement: string
  reqId?: string
  clientName?: string
  experience: string
  currentCompany: string
  submittedBy: string
  submittedOn: string
  status: string
  rejectionReason?: string
}

export const DEFAULT_SCREENSHOT_SUBMISSIONS: ScreenshotSubmission[] = [
  {
    id: 'SUB-201',
    candidateName: 'Alex Turner',
    requirement: 'Senior React Developer',
    reqId: 'REQ-2026-08-12-001',
    clientName: 'Accenture',
    experience: '7 Years 6 Months',
    currentCompany: 'Cognizant Technology Solutions',
    submittedBy: 'Marcus Chen',
    submittedOn: 'Aug 17, 2026',
    status: 'Submitted to Client',
  },
  {
    id: 'SUB-202',
    candidateName: 'Vidyasagar Gade',
    requirement: 'Cloud Solutions Architect',
    reqId: 'REQ-2026-08-12-003',
    clientName: 'Accenture',
    experience: '10 Years',
    currentCompany: 'Infosys Ltd',
    submittedBy: 'Priya Sharma',
    submittedOn: 'Aug 16, 2026',
    status: 'Interview Scheduled',
  },
  {
    id: 'SUB-203',
    candidateName: 'Suresh Kulkarni (Candidate)',
    requirement: 'PLM / PDM Lead Engineer',
    reqId: 'REQ-2026-08-12-004',
    clientName: 'Accenture',
    experience: '8 Years 2 Months',
    currentCompany: 'Wipro Limited',
    submittedBy: 'Suresh kulkarni',
    submittedOn: 'Aug 16, 2026',
    status: 'Rejected',
    rejectionReason: 'Technical evaluation score below threshold (C++ & PLM architecture round)',
  },
  {
    id: 'SUB-204',
    candidateName: 'Harish Gadipally (Lead Candidate)',
    requirement: 'Senior React / Fullstack Architect',
    reqId: 'REQ-2026-08-12-001',
    clientName: 'Accenture',
    experience: '12 Years',
    currentCompany: 'Metaforge IT Solutions',
    submittedBy: 'Harish Gadipally',
    submittedOn: 'Aug 15, 2026',
    status: 'Submitted to Client',
  },
  {
    id: 'SUB-205',
    candidateName: 'Rania Khalil',
    requirement: 'Java Cloud Architect',
    reqId: 'REQ-2026-08-06-005',
    clientName: 'Goldman Sachs',
    experience: '11 Years',
    currentCompany: 'Morgan Stanley',
    submittedBy: 'lakshmi.v Recruiter',
    submittedOn: 'Aug 14, 2026',
    status: 'Interview Scheduled',
  },
  {
    id: 'SUB-206',
    candidateName: 'Abhijit Narke',
    requirement: 'Java Lead Engineer',
    reqId: 'REQ-2026-08-06-005',
    clientName: 'Goldman Sachs',
    experience: '9 Years',
    currentCompany: 'Barclays India',
    submittedBy: 'Lingoji Pavani',
    submittedOn: 'Aug 14, 2026',
    status: 'Rejected',
    rejectionReason: 'Notice period exceeds 60 days budget limit',
  },
  {
    id: 'SUB-207',
    candidateName: 'Kanchan Meshram',
    requirement: 'Automotive Embedded Systems Engineer',
    reqId: 'REQ-2026-08-07-006',
    clientName: 'Tesla',
    experience: '6 Years 8 Months',
    currentCompany: 'Bosch Engineering',
    submittedBy: 'rahimoon Shaik',
    submittedOn: 'Aug 13, 2026',
    status: 'Submitted to Client',
  },
  {
    id: 'SUB-208',
    candidateName: 'Ben Wallace',
    requirement: 'Python ML Specialist',
    reqId: 'REQ-2026-08-07-007',
    clientName: 'Tesla',
    experience: '5 Years 4 Months',
    currentCompany: 'Nvidia India',
    submittedBy: 'Adirala sathvika',
    submittedOn: 'Aug 13, 2026',
    status: 'Rejected',
    rejectionReason: 'Salary expectation exceeds approved budget for Senior Machine Learning band',
  },
  {
    id: 'SUB-209',
    candidateName: 'Arpit Srivastav',
    requirement: 'SAP MM + Ariba Functional Lead',
    reqId: 'REQ-2026-07-20-009',
    clientName: 'ITC Infotech',
    experience: '8 Years',
    currentCompany: 'ITC Limited',
    submittedBy: 'Harini Sindey',
    submittedOn: 'Aug 12, 2026',
    status: 'Selected in Interview',
  },
  {
    id: 'SUB-210',
    candidateName: 'TEJENDRA RAMAN',
    requirement: '.NET Core Backend Architect',
    reqId: 'REQ-2026-06-08-001',
    clientName: 'LTTS Mobility',
    experience: '9 Years',
    currentCompany: 'HCL Technologies Ltd',
    submittedBy: 'Viswanath Reddy',
    submittedOn: 'Aug 11, 2026',
    status: 'Submitted to Client',
  },
]
