import { EnterpriseRoleData } from './rolesPermissionsData'

export const INITIAL_ROLES: EnterpriseRoleData[] = [
  {
    id: 'role-1',
    name: 'Super Admin',
    code: 'superadmin',
    description: 'Complete unrestricted access across all organizational modules, system settings, billing, and user governance.',
    userCount: 3,
    isSystem: true,
    lastUpdated: '10 Aug 2026',
    permissions: {
      req_view_all: true, req_create: true, req_edit: true, req_assign: true, req_delete: true,
      cand_search: true, cand_add: true, cand_export: true, cand_delete: true,
      sub_create: true, sub_view_all: true, sub_reassign: true, sub_move_stage: true,
      int_schedule: true, int_join_links: true, int_feedback: true, int_cancel: true,
      rep_view_exec: true, rep_view_recruiter: true, rep_export_csv: true,
      user_manage: true, role_manage: true, audit_logs: true,
    },
  },
  {
    id: 'role-2',
    name: 'Admin',
    code: 'admin',
    description: 'Full operational control over hiring teams, requirement assignments, candidate flow, and performance reports.',
    userCount: 8,
    isSystem: true,
    lastUpdated: '08 Aug 2026',
    permissions: {
      req_view_all: true, req_create: true, req_edit: true, req_assign: true, req_delete: false,
      cand_search: true, cand_add: true, cand_export: true, cand_delete: false,
      sub_create: true, sub_view_all: true, sub_reassign: true, sub_move_stage: true,
      int_schedule: true, int_join_links: true, int_feedback: true, int_cancel: true,
      rep_view_exec: true, rep_view_recruiter: true, rep_export_csv: false,
      user_manage: true, role_manage: false, audit_logs: false,
    },
  },
  {
    id: 'role-3',
    name: 'Team Lead',
    code: 'lead',
    description: 'Supervises assigned recruiter team, monitors daily submission targets, and manages interview scheduling.',
    userCount: 14,
    isSystem: true,
    lastUpdated: '05 Aug 2026',
    permissions: {
      req_view_all: true, req_create: false, req_edit: false, req_assign: true, req_delete: false,
      cand_search: true, cand_add: true, cand_export: true, cand_delete: false,
      sub_create: true, sub_view_all: true, sub_reassign: true, sub_move_stage: true,
      int_schedule: true, int_join_links: true, int_feedback: true, int_cancel: true,
      rep_view_exec: false, rep_view_recruiter: true, rep_export_csv: false,
      user_manage: false, role_manage: false, audit_logs: false,
    },
  },
  {
    id: 'role-4',
    name: 'Recruiter',
    code: 'recruiter',
    description: 'Individual recruiter focused on sourcing candidates, submitting to requirements, and tracking scheduled slots.',
    userCount: 32,
    isSystem: true,
    lastUpdated: '01 Aug 2026',
    permissions: {
      req_view_all: true, req_create: false, req_edit: false, req_assign: false, req_delete: false,
      cand_search: true, cand_add: true, cand_export: false, cand_delete: false,
      sub_create: true, sub_view_all: false, sub_reassign: false, sub_move_stage: true,
      int_schedule: true, int_join_links: true, int_feedback: true, int_cancel: false,
      rep_view_exec: false, rep_view_recruiter: true, rep_export_csv: false,
      user_manage: false, role_manage: false, audit_logs: false,
    },
  },
]
