export interface RecruiterOverviewItem {
  id: string
  name: string
  email: string
  avatar: string
  role: string
  teamLead: string
  clientNames: string[]
  totalRequirements: number
  totalSubmissions: number
  tatDays: number
  totalInterviews: number
  performanceStatus: 'Top Performer' | 'On Track' | 'Needs Attention'
}

export const INITIAL_RECRUITERS_DATA: RecruiterOverviewItem[] = [
  {
    id: 'rec-1',
    name: 'Harish Gadipally',
    email: 'harish.g@metaforgeit.com',
    avatar: 'H',
    role: 'Team Lead & Senior Recruiter',
    teamLead: 'Harish Gadipally (Self)',
    clientNames: ['Accenture', 'LTTS'],
    totalRequirements: 45,
    totalSubmissions: 142,
    tatDays: 1.5,
    totalInterviews: 38,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-2',
    name: 'Marcus Chen',
    email: 'm.chen@talentflow.io',
    avatar: 'M',
    role: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 14,
    totalSubmissions: 48,
    tatDays: 1.8,
    totalInterviews: 12,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-3',
    name: 'Priya Sharma',
    email: 'p.sharma@talentflow.io',
    avatar: 'P',
    role: 'IT Recruiter',
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 12,
    totalSubmissions: 36,
    tatDays: 2.1,
    totalInterviews: 9,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-4',
    name: 'Suresh kulkarni',
    email: 'suresh.k@talentflow.io',
    avatar: 'S',
    role: 'Technical Recruiter',
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 8,
    totalSubmissions: 24,
    tatDays: 2.4,
    totalInterviews: 6,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-5',
    name: 'lakshmi.v Recruiter',
    email: 'lakshmi.v@talentflow.io',
    avatar: 'L',
    role: 'Lead Recruiter',
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 18,
    totalSubmissions: 54,
    tatDays: 1.9,
    totalInterviews: 14,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-6',
    name: 'Lingoji Pavani',
    email: 'lingoji.p@talentflow.io',
    avatar: 'L',
    role: 'Senior Technical Recruiter',
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 10,
    totalSubmissions: 28,
    tatDays: 2.3,
    totalInterviews: 7,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-7',
    name: 'Arvind GR',
    email: 'arvind.g@talentflow.io',
    avatar: 'A',
    role: 'Technical Sourcing Recruiter',
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 6,
    totalSubmissions: 16,
    tatDays: 2.8,
    totalInterviews: 4,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-8',
    name: 'rahimoon Shaik',
    email: 'rahimoon.s@talentflow.io',
    avatar: 'R',
    role: 'Automotive Sourcing Specialist',
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 14,
    totalSubmissions: 42,
    tatDays: 2.0,
    totalInterviews: 11,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-9',
    name: 'Adirala sathvika',
    email: 'adirala.s@talentflow.io',
    avatar: 'A',
    role: 'Software Recruiter',
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 8,
    totalSubmissions: 22,
    tatDays: 2.5,
    totalInterviews: 5,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-10',
    name: 'Charlie Darwin',
    email: 'charlie.d@talentflow.io',
    avatar: 'C',
    role: 'Technical Sourcing Lead',
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 6,
    totalSubmissions: 20,
    tatDays: 2.2,
    totalInterviews: 4,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-11',
    name: 'Harini Sindey',
    email: 'harini.s@talentflow.io',
    avatar: 'H',
    role: 'Enterprise Recruiter',
    teamLead: 'Ray Diaz',
    clientNames: ['ITC Limited'],
    totalRequirements: 10,
    totalSubmissions: 32,
    tatDays: 2.1,
    totalInterviews: 8,
    performanceStatus: 'On Track',
  },
]
