export interface UnifiedTeamMember {
  id: string
  name: string
  email: string
  avatar: string
  role: string
  isTeamLead: boolean
  teamLead: string
  clientNames: string[]
  totalRequirements: number
  totalSubmissions: number
  tatDays: number
  totalInterviews: number
  performanceStatus: 'Top Performer' | 'On Track' | 'Needs Attention'
  membersCount?: number
  teamMembers?: string[]
}

export const INITIAL_MEMBERS_DATA: UnifiedTeamMember[] = [
  {
    id: 'rec-1',
    name: 'Harish Gadipally',
    email: 'harish.g@metaforgeit.com',
    avatar: 'H',
    role: 'Senior Recruiting Lead / Team Lead',
    isTeamLead: true,
    teamLead: 'Harish Gadipally (Self)',
    clientNames: ['Accenture', 'LTTS'],
    totalRequirements: 45,
    totalSubmissions: 142,
    tatDays: 1.5,
    totalInterviews: 38,
    performanceStatus: 'Top Performer',
    membersCount: 3,
    teamMembers: ['Marcus Chen', 'Priya Sharma', 'Suresh kulkarni'],
  },
  {
    id: 'rec-2',
    name: 'Marcus Chen',
    email: 'm.chen@talentflow.io',
    avatar: 'M',
    role: 'Senior Technical Recruiter',
    isTeamLead: false,
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 14,
    totalSubmissions: 48,
    tatDays: 1.8,
    totalInterviews: 12,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-3',
    name: 'Priya Sharma',
    email: 'p.sharma@talentflow.io',
    avatar: 'P',
    role: 'IT Recruiter',
    isTeamLead: false,
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 12,
    totalSubmissions: 36,
    tatDays: 2.1,
    totalInterviews: 9,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-4',
    name: 'Suresh kulkarni',
    email: 'suresh.k@talentflow.io',
    avatar: 'S',
    role: 'Technical Recruiter',
    isTeamLead: false,
    teamLead: 'Harish Gadipally',
    clientNames: ['Accenture'],
    totalRequirements: 8,
    totalSubmissions: 24,
    tatDays: 2.4,
    totalInterviews: 6,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-lead-2',
    name: 'Tom Walsh',
    email: 't.walsh@talentflow.io',
    avatar: 'T',
    role: 'Lead Recruiter — Financial Services',
    isTeamLead: true,
    teamLead: 'Tom Walsh (Self)',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 32,
    totalSubmissions: 98,
    tatDays: 1.9,
    totalInterviews: 25,
    performanceStatus: 'Top Performer',
    membersCount: 3,
    teamMembers: ['lakshmi.v Recruiter', 'Lingoji Pavani', 'Arvind GR'],
  },
  {
    id: 'rec-5',
    name: 'lakshmi.v Recruiter',
    email: 'lakshmi.v@talentflow.io',
    avatar: 'L',
    role: 'Lead Recruiter',
    isTeamLead: false,
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 18,
    totalSubmissions: 54,
    tatDays: 1.9,
    totalInterviews: 14,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-6',
    name: 'Lingoji Pavani',
    email: 'lingoji.p@talentflow.io',
    avatar: 'L',
    role: 'Senior Technical Recruiter',
    isTeamLead: false,
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 10,
    totalSubmissions: 28,
    tatDays: 2.3,
    totalInterviews: 7,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-7',
    name: 'Arvind GR',
    email: 'arvind.g@talentflow.io',
    avatar: 'A',
    role: 'Technical Sourcing Recruiter',
    isTeamLead: false,
    teamLead: 'Tom Walsh',
    clientNames: ['Goldman Sachs'],
    totalRequirements: 6,
    totalSubmissions: 16,
    tatDays: 2.8,
    totalInterviews: 4,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-lead-3',
    name: 'Nina Brooks',
    email: 'n.brooks@talentflow.io',
    avatar: 'N',
    role: 'Lead Recruiter — EV & Tech Sourcing',
    isTeamLead: true,
    teamLead: 'Nina Brooks (Self)',
    clientNames: ['Tesla'],
    totalRequirements: 28,
    totalSubmissions: 84,
    tatDays: 2.0,
    totalInterviews: 20,
    performanceStatus: 'Top Performer',
    membersCount: 3,
    teamMembers: ['rahimoon Shaik', 'Adirala sathvika', 'Charlie Darwin'],
  },
]
